services:
  ui:
    image: "davfer20/p1-ui:latest"
    container_name: dns_ui
    ports:
      - "80:80"
    environment:
      - REACT_APP_DNS_API=${dns_api_host}
      - REACT_APP_DNS_API_PORT=${dns_api_port}
