config:
  router:
    enabled: true
    replicas: 1
    name: router
    image: dandiego235/router-po:latest
    port: 8080
nginx-ingress-controller:
  namespaceOverride: public
  fullnameOverride: nginx-ingress-controller
  replicaCount: 1
  service:
    type: NodePort