FROM ubuntu:latest

RUN apg-get update \
    && apt-get install -y iptables

COPY nftable.nft /etc/iptables.conf

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]