services:
  apache:
    image: "dandiego235/apache-po:latest"
    container_name: apache
    ports:
      - "${apache_port}:80"
    restart: unless-stopped
  api:
    image: "dandiego235/rest-p2:latest"
    container_name: rest_api
    ports:
      - "${api_port}:5000"
    restart: unless-stopped
