services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - dandiego235/dns-api:1.0
        - dandiego235/dns-api:latest
    ports:
      - "5000:5000"
    container_name: dns_api
    networks:
      - shared-network
    restart: unless-stopped
    environment:
      - DNS_SERVER=8.8.8.8
      - DNS_PORT=53
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    container_name: dns_api
    volumes:
      - ./:/app
    working_dir: /app
    tty: true 
    ports:
      - "5000:5000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
