{{- if .Values.config.apache.enabled }}
{{- range .Values.config.apache.instances }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: private
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.config.apache.replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
      - name: {{ .name }}
        image: {{ .image }}
        ports:
          - containerPort: {{ .port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: private
  labels:
    app: {{ .name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .port }}
    protocol: TCP
    name: http
  selector:
    app: {{ .name }}
{{- end }}
{{- end }}
