{{- if .Values.config.asterisk.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.asterisk.name }}
  namespace: private
  labels:
    app: {{ .Values.config.asterisk.name }}
spec:
  replicas: {{ .Values.config.asterisk.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.config.asterisk.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.asterisk.name }}
    spec:
      containers:
        - name: {{ .Values.config.asterisk.name }}
          image: {{ .Values.config.asterisk.image }}
          ports:
            - containerPort: {{ .Values.config.asterisk.targetPort }}
            {{- range $port := untilStep 10000 10011 1 }}
            - containerPort: {{ $port }}
            {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.asterisk.name }}
  namespace: private
  labels:
    app: {{ .Values.config.asterisk.name }}
spec:
  type: ClusterIP
  ports:
    - name: sip
      port: {{ .Values.config.asterisk.port }}
      targetPort: {{ .Values.config.asterisk.targetPort }}
      protocol: UDP
    {{- range $i, $port := untilStep 10000 10011 1 }}
    - name: rtp-{{ $port }}  # Each port needs a unique name
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: UDP
    {{- end }}
  selector:
    app: {{ .Values.config.asterisk.name }}
{{- end}}