{{- if .Values.config.asterisk.enabled}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.asterisk.name }}
  namespace: private
  labels:
    app: {{ .Values.config.asterisk.name }}
spec:
  replicas: {{ .Values.config.asterisk.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.config.asterisk.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.asterisk.name }}
    spec:
      containers:
        - name: {{ .Values.config.asterisk.name }}
          image: {{ .Values.config.asterisk.image }}
          ports:
            - containerPort: {{ .Values.config.asterisk.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.asterisk.name }}
  namespace: private
  labels:
    app: {{ .Values.config.asterisk.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.config.asterisk.port }}
      targetPort: {{ .Values.config.asterisk.targetPort }}
      protocol: UDP
  selector:
    app: {{ .Values.config.asterisk.name }}
{{- end}}