services:
  ui:
    image: "davfer20/p1-ui:latest"
    container_name: dns_ui
    ports:
      - "80:80"
    environment:
      - REACT_APP_DNS_API=dns_api
      - REACT_APP_DNS_API_PORT=5000
  ui-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app # Bind mount: current directory to /app
    working_dir: /app
    tty: true # Keep container open for interactive shell
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_DNS_API=dns_api
      - REACT_APP_DNS_API_PORT=5000
    networks:
      - shared-network

networks:
  shared-network:
    external: true
