services:
  cache:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - dandiego235/zonal_cache:2.2
        - dandiego235/zonal_cache:latest
    image: "dandiego235/zonal_cache:latest"
    container_name: zonal_cache
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      REST_API: "host.docker.internal:3000" # "host.docker.internal:3000"
      APP_ID: "zonal_cache_CR" # "zonal_cache_dev"
      # API_KEY: "12345"
      FETCH_INTERVAL: "1" # "1"
      VERCEL_UI: "https://vercelui-eight.vercel.app" # "http://localhost:5173"
      VERCEL_TOKEN: "Rg7EZ7ORM8tSRfdQ23wLEPhx"
      VERCEL_EDGE_CONFIG_ID: "ecfg_ywndfxposwmc2jpmd6jv47mgjwji"
      COUNTRY: "DE"
    volumes:
      - subdomain_cache_data:/app/subdomain_cache

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true # Keep stdin open for interactive shell
    container_name: zonal_cache_dev
    volumes:
      - ./:/app # Bind mount: current directory to /app
    working_dir: /app
    tty: true # Keep container open for interactive shell
    ports:
      - "80:80"
      - "443:443"
    environment:
      REST_API: "host.docker.internal:3000"
      APP_ID: "zonal_cache_dev"
      API_KEY: "12345"
      FETCH_INTERVAL: "1"
      VERCEL_UI: "http://localhost:5173"

volumes:
  subdomain_cache_data:
