services:
  asterisk:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - asterisk-po:latest
        - asterisk-po:2.3
        - dandiego235/asterisk-po:latest
        - dandiego235/asterisk-po:2.3
    container_name: asterisk
    # volumes:
    #   - .:/app
    ports:
      - "5060:5060/udp"
      - "10000-10010:10000-10010/udp" # RTP media ports
