version: "3.8"
services:
  pokemon-api:
    build:
      context: .
      tags:
        - dandiego235/rest-p2:1
        - dandiego235/rest-p2:latest

    ports:
      - "5000:5000"
    restart: unless-stopped
