services:
  dns:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - dandiego235/dns-interceptor:5
        - dandiego235/dns-interceptor:latest
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true # Keep stdin open for interactive shell
    container_name: dns_dev
    volumes:
      - ./:/app # Bind mount: current directory to /app
    working_dir: /app
    tty: true # Keep container open for interactive shell
    ports:
      - "6001:53/udp"
    environment:
      DNS_API: "dns_api"
      DNS_API_PORT: "5000"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
