config:
  apache:
    enabled: true
    replicas: 1
    instances:
      - name: apache1
        image: dandiego235/apache-po:1.0
        port: 80
      - name: apache2
        image: dandiego235/apache-po:2.0
        port: 80
  asterisk:
    enabled: true
    replicas: 1
    name: asterisk
    image: dandiego235/asterisk-po:latest
    port: 5060
    targetPort: 5060
    protocol: UDP
    external_ip: ${EXTERNAL_IP}
    external_port: "30601"
  ingress:
    # Configuration for the Ingress obtained from https://kubernetes.io/docs/concepts/services-networking/ingress/
    name: nginx-ingress
    ingressClassName: nginx
    host: localhost
